export const MENU_SWITCH = 'MENU_SWITCH'
export const CHANGE_SCATTER_DATA = 'CHANGE_SCATTER_DATA'
export const SET_HIGHLIGHTED_POINT = 'SET_HIGHLIGHTED_POINT'
export const CHANGE_PLAYER = 'CHANGE_PLAYER'
